{
  "uid" : "208d8278a59ac760",
  "name" : "test_login01[case1]",
  "fullName" : "testcase.test_login.TestLogin#test_login01",
  "historyId" : "e61a131eafdd190c3a5f0c00ce5a5d87",
  "time" : {
    "start" : 1650292603196,
    "stop" : 1650292603201,
    "duration" : 5
  },
  "status" : "broken",
  "statusMessage" : "NameError: name 'act_res' is not defined",
  "statusTrace" : "self = <testcase.test_login.TestLogin object at 0x00000256600CCA30>\ncase = <comon.excel_util.CaseData object at 0x000002566007B6A0>\n\n    @pytest.mark.parametrize('case',ExcelUtil().read_excel('login'))\n    def test_login01(self, case):\n        print(case)\n        allure.attach(body=case.url, name='接口路径')\n        allure.attach(body=case.case_data, name='请求参数')\n        allure.attach(body=case.res, name='预期结果')\n        logger.info(\"*************** 开始执行用例 ***************\")\n        # logger.info('----------->开始执行测试案例:{}'.format(case['case_title']))\n        response = requests.get(url=case.url, data=eval(case.case_data))\n        # act_res=response.json()\n>       print(act_res)\nE       NameError: name 'act_res' is not defined\n\ntestcase\\test_login.py:26: NameError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "NameError: name 'act_res' is not defined",
    "statusTrace" : "self = <testcase.test_login.TestLogin object at 0x00000256600CCA30>\ncase = <comon.excel_util.CaseData object at 0x000002566007B6A0>\n\n    @pytest.mark.parametrize('case',ExcelUtil().read_excel('login'))\n    def test_login01(self, case):\n        print(case)\n        allure.attach(body=case.url, name='接口路径')\n        allure.attach(body=case.case_data, name='请求参数')\n        allure.attach(body=case.res, name='预期结果')\n        logger.info(\"*************** 开始执行用例 ***************\")\n        # logger.info('----------->开始执行测试案例:{}'.format(case['case_title']))\n        response = requests.get(url=case.url, data=eval(case.case_data))\n        # act_res=response.json()\n>       print(act_res)\nE       NameError: name 'act_res' is not defined\n\ntestcase\\test_login.py:26: NameError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "43f3eaae597c9c45",
      "name" : "接口路径",
      "source" : "43f3eaae597c9c45.attach",
      "type" : "text/plain",
      "size" : 42
    }, {
      "uid" : "46a18525c972efbf",
      "name" : "请求参数",
      "source" : "46a18525c972efbf.attach",
      "type" : "text/plain",
      "size" : 165
    }, {
      "uid" : "4f58d62195d959c8",
      "name" : "预期结果",
      "source" : "4f58d62195d959c8.attach",
      "type" : "text/plain",
      "size" : 62
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 3,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "testcase"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "Mikey"
  }, {
    "name" : "thread",
    "value" : "15044-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcase.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comon.excel_util.CaseData object at 0x000002566007B6A0>"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "208d8278a59ac760.json",
  "parameterValues" : [ "<comon.excel_util.CaseData object at 0x000002566007B6A0>" ]
}