{
  "uid" : "48c7ab7fd0958382",
  "name" : "输入正确的用户名和密码",
  "fullName" : "testcase.test_login.TestLogin#test_login01",
  "historyId" : "36f2f3d80fe1d5ee04c6e3c3e14bcb9c",
  "time" : {
    "start" : 1650273317525,
    "stop" : 1650273317612,
    "duration" : 87
  },
  "status" : "broken",
  "statusMessage" : "TypeError: 'CaseData' object is not subscriptable",
  "statusTrace" : "self = <testcase.test_login.TestLogin object at 0x00000231CBB87670>\ncase = <comon.excel_util.CaseData object at 0x00000231CBB9C340>\n\n    @pytest.mark.parametrize('case',ExcelUtil().read_excel('login'))\n    def test_login01(self, case):\n    \n        allure.dynamic.title(case.case_title)\n        allure.attach(body=case.url, name='接口路径')\n        allure.attach(body=case.case_data, name='请求参数')\n        allure.attach(body=case.res, name='预期结果')\n        logger.info(\"*************** 开始执行用例 ***************\")\n>       logger.info('----------->开始执行测试案例:{}'.format(case['CaseId']))\nE       TypeError: 'CaseData' object is not subscriptable\n\ntestcase\\test_login.py:24: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "TypeError: 'CaseData' object is not subscriptable",
    "statusTrace" : "self = <testcase.test_login.TestLogin object at 0x00000231CBB87670>\ncase = <comon.excel_util.CaseData object at 0x00000231CBB9C340>\n\n    @pytest.mark.parametrize('case',ExcelUtil().read_excel('login'))\n    def test_login01(self, case):\n    \n        allure.dynamic.title(case.case_title)\n        allure.attach(body=case.url, name='接口路径')\n        allure.attach(body=case.case_data, name='请求参数')\n        allure.attach(body=case.res, name='预期结果')\n        logger.info(\"*************** 开始执行用例 ***************\")\n>       logger.info('----------->开始执行测试案例:{}'.format(case['CaseId']))\nE       TypeError: 'CaseData' object is not subscriptable\n\ntestcase\\test_login.py:24: TypeError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "81643f7abdb57a82",
      "name" : "接口路径",
      "source" : "81643f7abdb57a82.attach",
      "type" : "text/plain",
      "size" : 13
    }, {
      "uid" : "b8d6e0ec2165c182",
      "name" : "请求参数",
      "source" : "b8d6e0ec2165c182.attach",
      "type" : "text/plain",
      "size" : 39
    }, {
      "uid" : "1a7fe3476b32d5ce",
      "name" : "预期结果",
      "source" : "1a7fe3476b32d5ce.attach",
      "type" : "text/plain",
      "size" : 30
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 3,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "testcase"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "小扁豆"
  }, {
    "name" : "thread",
    "value" : "9336-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcase.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comon.excel_util.CaseData object at 0x00000231CBB9C340>"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "48c7ab7fd0958382.json",
  "parameterValues" : [ "<comon.excel_util.CaseData object at 0x00000231CBB9C340>" ]
}