{
  "uid" : "49a6bc99008ead18",
  "name" : "test_login01[case0]",
  "fullName" : "testcase.test_login.TestLogin#test_login01",
  "historyId" : "36f2f3d80fe1d5ee04c6e3c3e14bcb9c",
  "time" : {
    "start" : 1650292603108,
    "stop" : 1650292603116,
    "duration" : 8
  },
  "status" : "broken",
  "statusMessage" : "NameError: name 'act_res' is not defined",
  "statusTrace" : "self = <testcase.test_login.TestLogin object at 0x00000256600B7640>\ncase = <comon.excel_util.CaseData object at 0x00000256600CC370>\n\n    @pytest.mark.parametrize('case',ExcelUtil().read_excel('login'))\n    def test_login01(self, case):\n        print(case)\n        allure.attach(body=case.url, name='接口路径')\n        allure.attach(body=case.case_data, name='请求参数')\n        allure.attach(body=case.res, name='预期结果')\n        logger.info(\"*************** 开始执行用例 ***************\")\n        # logger.info('----------->开始执行测试案例:{}'.format(case['case_title']))\n        response = requests.get(url=case.url, data=eval(case.case_data))\n        # act_res=response.json()\n>       print(act_res)\nE       NameError: name 'act_res' is not defined\n\ntestcase\\test_login.py:26: NameError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "NameError: name 'act_res' is not defined",
    "statusTrace" : "self = <testcase.test_login.TestLogin object at 0x00000256600B7640>\ncase = <comon.excel_util.CaseData object at 0x00000256600CC370>\n\n    @pytest.mark.parametrize('case',ExcelUtil().read_excel('login'))\n    def test_login01(self, case):\n        print(case)\n        allure.attach(body=case.url, name='接口路径')\n        allure.attach(body=case.case_data, name='请求参数')\n        allure.attach(body=case.res, name='预期结果')\n        logger.info(\"*************** 开始执行用例 ***************\")\n        # logger.info('----------->开始执行测试案例:{}'.format(case['case_title']))\n        response = requests.get(url=case.url, data=eval(case.case_data))\n        # act_res=response.json()\n>       print(act_res)\nE       NameError: name 'act_res' is not defined\n\ntestcase\\test_login.py:26: NameError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "6435420d57f8962c",
      "name" : "接口路径",
      "source" : "6435420d57f8962c.attach",
      "type" : "text/plain",
      "size" : 42
    }, {
      "uid" : "6f14fc0f2b696d0a",
      "name" : "请求参数",
      "source" : "6f14fc0f2b696d0a.attach",
      "type" : "text/plain",
      "size" : 167
    }, {
      "uid" : "b6043db10f5490f",
      "name" : "预期结果",
      "source" : "b6043db10f5490f.attach",
      "type" : "text/plain",
      "size" : 101
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 3,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "testcase"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "Mikey"
  }, {
    "name" : "thread",
    "value" : "15044-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcase.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comon.excel_util.CaseData object at 0x00000256600CC370>"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "49a6bc99008ead18.json",
  "parameterValues" : [ "<comon.excel_util.CaseData object at 0x00000256600CC370>" ]
}