{
  "uid" : "4f61bdfb74e69719",
  "name" : "输入错误的用户名",
  "fullName" : "testcase.test_login.TestLogin#test_login01",
  "historyId" : "e61a131eafdd190c3a5f0c00ce5a5d87",
  "time" : {
    "start" : 1650273317700,
    "stop" : 1650273317706,
    "duration" : 6
  },
  "status" : "broken",
  "statusMessage" : "TypeError: 'CaseData' object is not subscriptable",
  "statusTrace" : "self = <testcase.test_login.TestLogin object at 0x00000231CBB98700>\ncase = <comon.excel_util.CaseData object at 0x00000231CBB4B5E0>\n\n    @pytest.mark.parametrize('case',ExcelUtil().read_excel('login'))\n    def test_login01(self, case):\n    \n        allure.dynamic.title(case.case_title)\n        allure.attach(body=case.url, name='接口路径')\n        allure.attach(body=case.case_data, name='请求参数')\n        allure.attach(body=case.res, name='预期结果')\n        logger.info(\"*************** 开始执行用例 ***************\")\n>       logger.info('----------->开始执行测试案例:{}'.format(case['CaseId']))\nE       TypeError: 'CaseData' object is not subscriptable\n\ntestcase\\test_login.py:24: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "TypeError: 'CaseData' object is not subscriptable",
    "statusTrace" : "self = <testcase.test_login.TestLogin object at 0x00000231CBB98700>\ncase = <comon.excel_util.CaseData object at 0x00000231CBB4B5E0>\n\n    @pytest.mark.parametrize('case',ExcelUtil().read_excel('login'))\n    def test_login01(self, case):\n    \n        allure.dynamic.title(case.case_title)\n        allure.attach(body=case.url, name='接口路径')\n        allure.attach(body=case.case_data, name='请求参数')\n        allure.attach(body=case.res, name='预期结果')\n        logger.info(\"*************** 开始执行用例 ***************\")\n>       logger.info('----------->开始执行测试案例:{}'.format(case['CaseId']))\nE       TypeError: 'CaseData' object is not subscriptable\n\ntestcase\\test_login.py:24: TypeError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "7a534896a1b69894",
      "name" : "接口路径",
      "source" : "7a534896a1b69894.attach",
      "type" : "text/plain",
      "size" : 13
    }, {
      "uid" : "291d4c1b3a0a7c41",
      "name" : "请求参数",
      "source" : "291d4c1b3a0a7c41.attach",
      "type" : "text/plain",
      "size" : 40
    }, {
      "uid" : "b87bce6c69c2e62e",
      "name" : "预期结果",
      "source" : "b87bce6c69c2e62e.attach",
      "type" : "text/plain",
      "size" : 30
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 3,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "testcase"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "小扁豆"
  }, {
    "name" : "thread",
    "value" : "9336-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcase.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comon.excel_util.CaseData object at 0x00000231CBB4B5E0>"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "4f61bdfb74e69719.json",
  "parameterValues" : [ "<comon.excel_util.CaseData object at 0x00000231CBB4B5E0>" ]
}