{
  "uid" : "9ec18d864edf7440",
  "name" : "test_login01[case0]",
  "fullName" : "testcase.test_login.TestLogin#test_login01",
  "historyId" : "36f2f3d80fe1d5ee04c6e3c3e14bcb9c",
  "time" : {
    "start" : 1650340817289,
    "stop" : 1650340817289,
    "duration" : 0
  },
  "status" : "failed",
  "statusMessage" : "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntestcase\\test_login.py:75: AssumptionFailure\n>>\tpytest.assume(flag == False)\nAssertionError: assert False",
  "statusTrace" : "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               testcase\\test_login.py:75: AssumptionFailure\nE               >>\tpytest.assume(flag == False)\nE               AssertionError: assert False\n\nD:\\Python\\lib\\site-packages\\six.py:718: FailedAssumption",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntestcase\\test_login.py:75: AssumptionFailure\n>>\tpytest.assume(flag == False)\nAssertionError: assert False",
    "statusTrace" : "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               testcase\\test_login.py:75: AssumptionFailure\nE               >>\tpytest.assume(flag == False)\nE               AssertionError: assert False\n\nD:\\Python\\lib\\site-packages\\six.py:718: FailedAssumption",
    "steps" : [ {
      "name" : "预期与结果",
      "time" : {
        "start" : 1650340817306,
        "stop" : 1650340817306,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "91c9688d11df2eaf",
        "name" : "预期",
        "source" : "91c9688d11df2eaf.json",
        "type" : "application/json",
        "size" : 100
      }, {
        "uid" : "3d02215a097af94a",
        "name" : "结果",
        "source" : "3d02215a097af94a.json",
        "type" : "application/json",
        "size" : 101
      } ],
      "parameters" : [ ],
      "attachmentsCount" : 2,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : true
    }, {
      "name" : "响应失败原因",
      "time" : {
        "start" : 1650340817306,
        "stop" : 1650340817307,
        "duration" : 1
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "b23faf56ad4b629c",
        "name" : "数据",
        "source" : "b23faf56ad4b629c.txt",
        "type" : "text/plain",
        "size" : 64
      } ],
      "parameters" : [ ],
      "attachmentsCount" : 1,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : true
    }, {
      "name" : "断言结果",
      "time" : {
        "start" : 1650340817307,
        "stop" : 1650340817372,
        "duration" : 65
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    } ],
    "attachments" : [ {
      "uid" : "8444005769d0fe85",
      "name" : "接口路径",
      "source" : "8444005769d0fe85.attach",
      "type" : "text/plain",
      "size" : 42
    }, {
      "uid" : "25970867828a1198",
      "name" : "请求参数",
      "source" : "25970867828a1198.attach",
      "type" : "text/plain",
      "size" : 167
    }, {
      "uid" : "573f1fc57501d001",
      "name" : "预期结果",
      "source" : "573f1fc57501d001.attach",
      "type" : "text/plain",
      "size" : 100
    }, {
      "uid" : "7f91f4b31a23d8bc",
      "name" : "响应结果",
      "source" : "7f91f4b31a23d8bc.attach",
      "type" : "text/plain",
      "size" : 16
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 7,
    "shouldDisplayMessage" : true,
    "stepsCount" : 3,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "testcase"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "Mikey"
  }, {
    "name" : "thread",
    "value" : "11552-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcase.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comon.excel_util.CaseData object at 0x000001AA7D17D4F0>"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "9ec18d864edf7440.json",
  "parameterValues" : [ "<comon.excel_util.CaseData object at 0x000001AA7D17D4F0>" ]
}